### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by mzgol** [olov/ng-annotate#129]
Did you think about running automated tests on Travis (for UNIX) and AppVeyor (for Windows)? Or do you have any other CI setup enabled that's just not published in the repository?

**Comment by olov** [comment]
I haven't really thought about that to be honest. The current build process takes less than 3 seconds and I build before every push. I push quite rarely and PR's happens rarely. Very few run ng-annotate from master. I guess setting up a CI for ng-annotate seems like adding ceremony for little gain, but I could be mistaken? Also note that the recent incorrect-shebang problem would not necessarily have been caught by CI at all, because most of the time `/bin/sh` supports bashisms.

**Comment by mzgol** [comment]
That's what I thought but do you test on the following at least before every release?

1. Node 0.10, 0.11 & io.js? Sth can fail in one & pass in the other.
2. The above both on UNIX & Windows?

This is not a problem in 95% of cases but there are always these 5%. :)

You're right it might not catch all the issues like the `/bin/sh` one.

**Comment by olov** [comment]
That's true. I just test with the version of node I happen to use on my Mac.

While I don't have the time to do it (or rather ES6 support is a better use of my hours) a contribution consisting of CI setup and maintenance would be welcome!

**Comment by olov** [comment]
now integrated with 1.1.0
