### ISSUE TITLE
Support for angular-dashboard-provider

### ISSUE THREAD

**Issue by sdorra** [olov/ng-annotate#133]
It is possible that you add support for controller, resolve, edit.controller and edit.resolve of the [angular-dashboard-framework](https://github.com/sdorra/angular-dashboard-framework)? Here is a short example of those methods:

```javascript
angular.module('myModule', ['adf.provider'])
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('myWidget', {
        title: 'My Widget',
        controller: function($http){
           // control something
        },
        resolve: {
          one: function($http, config){
            // resolve something
          },
          two: function($http, config){
            // resolve something
          }
        },
        edit: {
          controller: function($http){
            // control something
          },
          resolve: {
            editone: function($http, config){
              // resolve something
            },
            edittwo: function($http, config){
              // resolve something
            }
        }
      });
});
```

**Comment by olov** [comment]
Sure. Can you clarify the API - is it always `dashboardProvider.widget("name", {..})`?

**Comment by sdorra** [comment]
Thank you very much. Yes, it is always ```dashboardProvider.widget("name", {..})```.

**Comment by olov** [comment]
Looking into this again, perhaps my "Sure" was a bit premature. I'm not sure. ng-annotate is currently trained to detect patterns from angular core, ui-router, angular-ui and angular material design. All of those are high profile angular projects. The question now is where to draw the line in terms of what projects to support. We can't support everything, because that will increase the risk of false positives.

A variant could be to support any contributions we get but make them disabled by default, i.e. {enable: ["sdorra/angular-dashboard-framework"]}.

I welcome others thoughts on this topic, @mzgol @omsmith et al!

@sdorra meanwhile would you like to try to convert your PR into a plugin?

**Comment by mzgol** [comment]
> A variant could be to support any contributions we get but make them disabled by default, i.e. {enable: ["sdorra/angular-dashboard-framework"]}.

Seems like a good idea, otherwise with a growing number of Angular-based projects with own DI patterns false positives are quite probable.

**Comment by sdorra** [comment]
> A variant could be to support any contributions we get but make them disabled by default, i.e. {enable: ["sdorra/angular-dashboard-framework"]}.

Sounds good. 

@olov i was able to implement the adf annotation within a plugin. Should i create a new PR with the plugin. E.g.:

plugins/sdorra/angular-dashboard-framework.js

**Comment by olov** [comment]
Yes please, create is as `optionals/angular-dashboard-framework.js` and `tests/optionals/angular-dashboard-framework.js` and `tests/optionals/angular-dashboard-framework.annotated.js`. I'll hook it up to API and cmdline options. Thanks!

**Comment by olov** [comment]
fixed in https://github.com/olov/ng-annotate/commit/cd413b09ff8d824110dbb01eb943137ab7b45f79

Pass `--enable angular-dashboard-framework` to use it. Is part of the upcoming 1.0 release.
