### ISSUE TITLE
Inconsistent line ending introduced

### ISSUE THREAD

**Issue by rcollette** [olov/ng-annotate#134]
It appears that gulp-ng-annotate is introducing an inconsistent line ending, which winds up throwing up a warning in Visual Studio.

![lineending](https://cloud.githubusercontent.com/assets/136476/5994251/e4f91524-aa39-11e4-97b8-71d89e157316.png)

The following is the typescript source

![source](https://cloud.githubusercontent.com/assets/136476/5994363/02ec638e-aa3e-11e4-970e-79abbf78df3a.png)

**Comment by olov** [comment]
Thanks for filing an issue and sorry about that. Would you be able to execute your minimal example using ng-annotate directly, i.e. `npm install -g ng-annotate` and `ng-annotate -a infile.js -o outfile.js`, then upload infile.js and outfile.js somewhere? Thanks!

**Comment by olov** [comment]
Also, which version of node and ng-annotate are you using?

**Comment by rcollette** [comment]
Files are here
https://drive.google.com/folderview?id=0Bx7rOpBwQPKgfndJSjRMUURBWjQ2MVdZQzhLZzVtOHh4eENPblEyelZUQ1Y0bFR5QWRSQ1U&usp=sharing

Node version 0.10.36
ng-annotate version 0.15.4

**Comment by olov** [comment]
can you update the infile again? Tt's currently a copy of outfile.js

**Comment by rcollette** [comment]
Ok.  Not sure what happened there but I opened it from google drive and it appears to be the correct one.

**Comment by olov** [comment]
Ok thanks that helped. This is what happens: Your infile is encoded with Unix line-endings (LF) instead of traditional Windows line-endings (CR+LF). ng-annotate detects that you run node under Windows and for that reason assumes that you want the added newline to be CR+LF.

I'm not sure what to do with this. Perhaps we should choose newlines based on existing infile content rather than platform.. Thoughts from @smrq (I think you were involved in newlines previously)?

We could also provide an overriding `{newlines: "unix" | "windows"}` option.

@rcollette This will get adressed one way or another in an upcoming release, for now live with the warning or perform line-endings conversion after ng-annotate in your build pipeline.

**Comment by omsmith** [comment]
Perhaps something like [detect-newline](https://www.npmjs.com/package/detect-newline)?

**Comment by olov** [comment]
@omsmith something like that but a bit simpler, we can just re-use whatever newline was used on the previous line to save some cycles. My reasoning is that if a file already uses a mix of CR and CR+LF then it doesn't matter what we add.

**Comment by omsmith** [comment]
Previous newline makes sense to me

**Comment by rcollette** [comment]
I'm not sure why the platform line endings are being removed.  It's either sourcemaps or the typescript compiler.   Looking at the previous newline (or following newline if none is preceding), sounds like a good idea. Here's my gulp

````
return gulp.src(['app/**/*.ts'])
        .pipe(plumber())
        .pipe(addsrc('typings/**/*.ts'))
        .pipe(sourcemaps.init())
        .pipe(ts(tsProjectMode, undefined, ts.reporter.fullReporter(true))).js
        .pipe(ngAnnotate({
            remove: false,
            add: true,
            gulpWarnings: false //typescript removes base path for some reason.  Warnings result that we don't want to see.
        }))
        .pipe(sourcemaps.write('.', { includeContent: false }))
        .pipe(gulp.dest('app'));
````
