### ISSUE TITLE
Add support for multiple input files as a pattern matching path

### ISSUE THREAD

**Issue by Kiougar** [olov/ng-annotate#147]
I think it would be great to add support for multiple files by specifying a source folder with pattern matching and a destination folder for the output files.

eg: `ng-annotate --source /static/js/*.js --dest /dist/static/js/`

We could use the [glob](https://www.npmjs.com/package/glob) node package to match the files.

I can help developing it or I can provide a pull request if you like but I would need help/guidance.

**Comment by omsmith** [comment]
I could see supporting multiple files, but wouldn't be a huge fan of globbing logic within _ng-annotate_. That's what shells are for.

Could always do something with _find_, such as,

`find static/js -iname '*.js' -exec sh -c 'ng-annotate {} > /dist/statis/js/{}' \;`

**Comment by Kiougar** [comment]
Thanks for the shell solution (was wondering how I could do it with the current ng-annotate release) but I wanted an OS independent one.
I suggested glob as an example solution which is OS independent.

Let alone the glob, how would you propose supporting multiple files be done?

**Comment by olov** [comment]
For now ng-annotate stays ~small by not including such features. It's a slippery slope because as soon as your proposed feature would be implemented, another request for implementing file system watching would come. Then caching, then bundling, then.. If a shell one-liner doesn't' cut it then there are plenty of cross platform build tools you can choose from (see README). For that reason => closing.

**Comment by Kiougar** [comment]
Ok, understood. Thanks for replying. :)
