### ISSUE TITLE
Parse error with 'new Date()' Instanciation

### ISSUE THREAD

**Issue by tomahim** [olov/ng-annotate#157]
Hi,

I have an issue with date instanciation, which seems to be reproducible only when using directy int like this on my source code : 

new Date(2015, 01 ,01)

When I build I have this error : couldn't process source due to parse error. Invalid number.

If I use another way to instanciate my date, with string or variables I have no problem.

**Comment by olov** [comment]
In ES5 and later octal identifiers like `01` are supposed to be syntactic errors, iff you're in strict mode. So what's happening here is that Acorn is throwing an error. You may have ended up in strict mode unknowingly after concatenating files (if so check that out because it may give you other problems not related to ng-annotate).

So either 1) use `1` instead of `2` or 2) don't use strict mode.

If you think that the problems happen outside of strict mode then please provide a minimal example and re-open the bug.

**Comment by tomahim** [comment]
Yes you are right, I am in strict mode. 
Thank you for the explanation, I didn't knew about this ES5 behavior.
