### ISSUE TITLE
Not able to annotate directive controller dependency injections

### ISSUE THREAD

**Issue by mudassir0909** [olov/ng-annotate#170]
```javascript
(function() {
    'use strict';

    angular
        .module('app.widgets')
        .directive('directiveName', directiveName);

    function directiveName(someService) { //This is working
        return {
            controller: function(anotherService) { //No annotations generated for this one
        }
     }
   }
```

**Comment by olov** [comment]
```js
~/projects/ng-annotate % ./ng-annotate-harmony -a tests-issues/issue-170.js
(function() {
    'use strict';

    angular
        .module('app.widgets')
        .directive('directiveName', directiveName);

    function directiveName(someService) { //This is working
        return {
            controller: ["anotherService", function(anotherService) { //No annotations generated for this one
        }]
     }
    }
    directiveName.$inject = ["someService"];
});
```

Works just fine in ng-annotate 1.0. You're most likely using an old version so please upgrade.

**Comment by mudassir0909** [comment]
@olov The question is about the annotations for the controller, I have to wrap it inside array is it ?

Basically, if I do 

```javascript
   angular
        .module('app.widgets')
        .directive('directiveName', directiveName);

    function directiveName(someService) { //This is working
        return {
            controller: Controller
        }
     }

     function Controller(injectableDependency) {
    }
   }
```

```
Controller.$inject = ['injectableDependency'];
```
wont be generated

**Comment by olov** [comment]
Well that's different compared to your first example. ng-annotate does not understand the pattern `return {controller: <reference>}` so I suggest you add `"ngInject";` inside of `function Controller`.

For future bug reports, please include input, expected output, actual output, ng-annotate version to save me some time.

**Comment by levin81** [comment]
Using latest grunt-ng-annotate with ng-annotate 1.0.2 installed, this still doesn't work:

    (function() {
	'use strict';
	
	angular
		.module('app.components')
		.directive("cvSaveButton", cvSaveButton);
	
	function cvSaveButton() {
		var directive = {
			restrict: 'E',
			templateUrl: 'app/components/saveButton/saveButtonView.html',
			scope: {
				form: '=',
				save: '&',
				waiting: '='
			},
			controller: saveButtonController,
			controllerAs: 'vm',
			bindToController: true,
		};
		
		function saveButtonController($scope) {
			var vm = this;
			vm.tooltip = '';
			
			$scope.$watchGroup(['vm.form.$pristine', 'vm.form.$invalid'], function() {
				/* ... */
			});
		}
	
		return directive;
	}
	
    })();

The input and output are the same, no inject is inserted for the controller unless I use ngInject. Is this expected?

**Comment by olov** [comment]
@levin81 that's not a form ng-annotate understands. do `return {` in cvSaveButton and things will work.

**Comment by levin81** [comment]
Thanks, I changed it and it worked. Could this be supported? As this form is recommended both in https://github.com/johnpapa/angular-styleguide#directives and in https://docs.angularjs.org/api/ng/service/$compile

**Comment by bartvanderwal** [comment]
+1!

I'm also experiencing this issue. And I am also following John Papa's styleguide, which is by now also endorsed by the angular team itself.

**Comment by dave-newson** [comment]
Just to necro this issue again, I'm here also because of this slight discrepancy between ng-annotate behaviour and the John Papa style guide, too.

Because I wasted 45 minutes on this, here's a recap for anyone else (and google):

The Angular exception raised takes this form:
> Error: [$injector:unpr] Unknown provider: iProvider <- i

Because the minifier has minified the arguments on the Controller function, but ng-annotate couldn't identify the _Directive's controller_ as a controller and thus failed to generate the `$inject` call.

The difference, as pointed out by @olov, is in returning the directive definition rather than setting it on an object and _then_ returning:

## Does Not Work
```js
        var directive = {
            restrict: 'EA',
            controller: MyDirectiveController,
        };
        return directive;

        function MyDirectiveController($scope) {
            $scope.someVar = "Hello World";
        }
```

## Does Work
```js
        return {
            restrict: 'EA',
            controller: MyDirectiveController,
        };

        function MyDirectiveController($scope) {
            $scope.someVar = "Hello World";
        }
```

It's a minor annoyance with a simple workaround, but as the Angular errors for minified controller arguments are so completely useless (and this is _why_ we use ng-annotate) it's quite the time waster when you bump into it.

Citing @bartvanderwal comment about John Papa's guide being endorsed by the Angular team, it would be great if something could be done to support this in the future.

This was confirmed using `gulp-ng-annotate 2.0.0` with `ng-annotate 1.2.1` under the hood.
