### ISSUE TITLE
If running on Node.JS 0.12.5 I get parse errors on minified files

### ISSUE THREAD

**Issue by AndyOGo** [olov/ng-annotate#176]
ngAnnotate breaks with minified files: "error: couldn't process source due to parse error".
I get this errors if I read in iconic.min.js -> https://useiconic.com/tools/iconic-js/

If i roll back node to version 0.10.33 it works perfectly.

**Comment by olov** [comment]
You shouldn't run ng-annotate on minified and/or third-party code so get rid of that in your build process.

Feel free to re-open if you can provide more information for the issue, such as a reduced test case.

**Comment by AndyOGo** [comment]
Indeed, I changed my build process as a quick fix.
But anyway, any minified file should not be the cause of wrong behaviour, since it is valid ECMAScript code...

**Comment by olov** [comment]
There's a difference between a script being runnable by popular JS engines and being valid ES. I suspect that iconic.min.js isn't the latter, perhaps due to a combination of opting into strict mode and using some forbidden syntactic construct. But again, you haven't provided enough information so I'm just guessing.
