### ISSUE TITLE
support angular 1.5 component()

### ISSUE THREAD

**Issue by kether667** [olov/ng-annotate#226]
currently controller of the component is not properly annotated

**Comment by olov** [comment]
Please provide issues in the form of input, expected output, actual output. Include the version of ng-annotate and node that you are using. With pull requests, please include changes to the tests as well (tests/original.js, tests/with_annotations.js).

**Comment by Frank3K** [comment]
@kether667: This was added in 5bfb3b124efd29c920fe13e871e92549260d2f62. Make sure you have the latest `gulp-ng-annotate` and dependencies. I had the same issue and found out that not all dependencies were up to date.

**Comment by kether667** [comment]
thanks, yea gulp-ng-annotate specifies 'ng-annotate': '^1.0.0', which doesn't update when typing npm install 

after i remove ng-annotate from node_modules it downloaded newest version

**Comment by opadillaintegrify** [comment]
This isn't working quite right for me.  Here's my source file:
[intTaskExcelImportConfig.txt](https://github.com/olov/ng-annotate/files/172608/intTaskExcelImportConfig.txt)

$ ng-annotate -a intTaskExcelImportConfig.txt > annotated.txt

Actual output:
annotated.txt is identical to intTaskExcelImportConfig.txt

Expected output:
I expected to see this line in annotated.txt:
Ctrl.$inject = ["$scope", "$timeout", "LocalizationService"];

I did notice that if I add  /*@ngInject*/ then I do get the expected output.   It'd be great if I didn't have to manually add this to my components since I don't do it in my directives.

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
