### ISSUE TITLE
How does the inline sourcemap correspond to the transformed source that really doesn't exist on file system?

### ISSUE THREAD

**Issue by crocket** [olov/ng-annotate#75]
The original source doesn't match the transformed source, thus I guess that the sourcemap will not accurately map to the original source.

Am I right?
Or, do sourcemaps make browsers display the transformed source that doesn't exist on file system?

**Comment by cherrydev** [comment]
Hey, just for everyone to know, [here is an example](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md) of how to do this.  You just go back to using gulp-sourcemaps directly, init-ing it immediately after you've created the buffered stream, but passing it the `{loadMaps: true}` option.  This will cause gulp-sourcemaps to read the existing sourcemaps that were output by browserify as its method of initialization, instead of using the contents of the original files (which it doesn't have access to).  This completely fixed my problem with ng-annotate corrupting my source maps.

**Comment by olov** [comment]
@cherrydev thanks for sharing!
