### ISSUE TITLE
$injector.invoke calls aren't correctly annotated

### ISSUE THREAD

**Issue by samaxes** [olov/ng-annotate#86]
The following code which is inside a directive's link function does not get annotated:

``` js
// Compile new element
$injector.invoke(function($compile) {
  $compile(myElement)(scope);
});
```

Previously posted at mzgol/grunt-ng-annotate#15.

**Comment by levithomason** [comment]
Our use case involves running some setup code before bootstrapping angular.  This setup code calls the $injector.invoke() method.  Since it is before angular bootstraps, it is outside of any angular modules.

I see the comment in [460913](https://github.com/olov/ng-annotate/commit/460913e83d4d21bf0e39e957cdbacc3638463e8e)
>// matchInjectorInvoke must happen before matchRegular
// to prevent false positive ($injector.invoke() outside module)

Our code, run on page load in a IIF at the global level, not annotated:
```javascript
var $injector = angular.injector();

$injector.invoke(function($kinvey, ENV) {
// do stuff, then bootstrap angular
});
```

Thanks in advance.

**Comment by olov** [comment]
@levithomason the annotate-only-when-inside-angular-modules is to reduce the risk of false positives. ngInject to the rescue! Try: `$injector.invoke(/*@ngInject*/function($kinvey, ENV) { ... })`.

**Comment by levithomason** [comment]
Awesome, still better than manually injecting :)  Thanks
